package generate

import "core:fmt"
import fp "core:path/filepath"
import "core:strings"

g_ojson_prefix: string
g_package_prefixes: map[string]string

generate_code :: proc(
	structs: []Struct_Info,
	package_name: string,
	output_dir: string = "",
	ojson_import: string = "",
	allocator := context.allocator,
) -> string {
	sb := strings.builder_make(allocator)

	g_ojson_prefix = ojson_import != "" ? "oj." : ""

	Package_Info :: struct {
		name:        string,
		source_dir:  string,
		import_path: string,
	}
	packages := make(map[string]Package_Info, allocator = allocator)
	defer delete(packages)

	for info in structs {
		if info.source_package == "" || info.source_dir == "" {
			continue
		}

		if info.source_package == package_name {
			continue
		}

		if info.source_dir not_in packages {
			import_path, _ := fp.rel(output_dir, info.source_dir)
			packages[info.source_dir] = Package_Info {
				name        = info.source_package,
				source_dir  = info.source_dir,
				import_path = import_path,
			}
		}
	}

	g_package_prefixes = make(map[string]string, allocator = allocator)
	for dir, pkg in packages {
		g_package_prefixes[dir] = fmt.tprintf("%s.", pkg.name)
	}

	strings.write_string(&sb, "// Code generated by ojson generator. DO NOT EDIT.\n")
	strings.write_string(&sb, "package ")
	strings.write_string(&sb, package_name)
	strings.write_string(&sb, "\n\n")

	for _, pkg in packages {
		fmt.sbprintf(&sb, "import %s \"%s\"\n", pkg.name, pkg.import_path)
	}
	if ojson_import != "" {
		fmt.sbprintf(&sb, "import oj \"%s\"\n", ojson_import)
	}
	if len(packages) > 0 || ojson_import != "" {
		strings.write_string(&sb, "\n")
	}

	for info, i in structs {
		generate_unmarshal_proc(&sb, info)
		if i < len(structs) - 1 {
			strings.write_string(&sb, "\n")
		}
	}

	return strings.to_string(sb)
}

get_type_prefix :: proc(info: Struct_Info) -> string {
	if info.source_dir == "" {
		return ""
	}
	if prefix, ok := g_package_prefixes[info.source_dir]; ok {
		return prefix
	}
	return ""
}

generate_unmarshal_proc :: proc(sb: ^strings.Builder, info: Struct_Info) {
	lower_name := to_snake_case(info.name)
	type_prefix := get_type_prefix(info)
	type_name := fmt.tprintf("%s%s", type_prefix, info.name)

	fmt.sbprintf(sb, "// Unmarshals JSON into %s\n", info.name)
	if info.source_package != "" && info.source_file != "" {
		fmt.sbprintf(sb, "// Source: %s (%s)\n", info.source_package, info.source_file)
	}

	fmt.sbprintf(
		sb,
		"unmarshal_%s :: proc(r: ^%sReader, path: string = \"\") -> (result: %s, err: %sError) {{\n",
		lower_name,
		g_ojson_prefix,
		type_name,
		g_ojson_prefix,
	)
	fmt.sbprintf(sb, "\telem, elem_err := %selement_at(r, path)\n", g_ojson_prefix)
	fmt.sbprintf(sb, "\tif elem_err != .OK do return result, elem_err\n")
	fmt.sbprintf(sb, "\treturn unmarshal_%s_elem(r, elem)\n", lower_name)
	fmt.sbprintf(sb, "}}\n\n")

	fmt.sbprintf(sb, "// Unmarshals JSON element into %s\n", info.name)

	fmt.sbprintf(
		sb,
		"unmarshal_%s_elem :: proc(r: ^%sReader, elem: %sElement) -> (result: %s, err: %sError) {{\n",
		lower_name,
		g_ojson_prefix,
		g_ojson_prefix,
		type_name,
		g_ojson_prefix,
	)

	for field in info.fields {
		generate_field_read(sb, field, info)
	}

	strings.write_string(sb, "\treturn\n")
	strings.write_string(sb, "}\n")
}

generate_field_read :: proc(sb: ^strings.Builder, field: Field_Info, parent: Struct_Info) {
	oj := g_ojson_prefix
	tp := get_type_prefix(parent)

	switch field.type_kind {
	case .String:
		fmt.sbprintf(
			sb,
			"\tresult.%s, err = %sread_string_elem(r, elem, \"%s\")\n",
			field.odin_name,
			oj,
			field.json_name,
		)
		strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found do return\n\n")

	case .Int:
		fmt.sbprintf(
			sb,
			"\tresult.%s, err = %sread_int_elem(r, elem, \"%s\")\n",
			field.odin_name,
			oj,
			field.json_name,
		)
		strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found do return\n\n")

	case .I64:
		fmt.sbprintf(
			sb,
			"\tresult.%s, err = %sread_i64_elem(r, elem, \"%s\")\n",
			field.odin_name,
			oj,
			field.json_name,
		)
		strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found do return\n\n")

	case .F64:
		fmt.sbprintf(
			sb,
			"\tresult.%s, err = %sread_f64_elem(r, elem, \"%s\")\n",
			field.odin_name,
			oj,
			field.json_name,
		)
		strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found do return\n\n")

	case .Bool:
		fmt.sbprintf(
			sb,
			"\tresult.%s, err = %sread_bool_elem(r, elem, \"%s\")\n",
			field.odin_name,
			oj,
			field.json_name,
		)
		strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found do return\n\n")

	case .I8, .I16, .I32:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: i64\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_i64_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s%s(val)\n",
			field.odin_name,
			tp,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .U8, .U16, .U32, .U64, .Uint:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: i64\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_i64_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s%s(val)\n",
			field.odin_name,
			tp,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .F16, .F32:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: f64\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_f64_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s%s(val)\n",
			field.odin_name,
			tp,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .Enum:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: int\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_int_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s%s(val)\n",
			field.odin_name,
			tp,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .Distinct:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: int\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_int_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s%s(val)\n",
			field.odin_name,
			tp,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .Struct:
		nested_lower := to_snake_case(field.type_name)
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(
			sb,
			"\t\tnested_elem, nested_err := %sobj_element_from(r, elem, \"%s\")\n",
			oj,
			field.json_name,
		)
		fmt.sbprintf(sb, "\t\tif nested_err == .OK {{\n")
		fmt.sbprintf(
			sb,
			"\t\t\tresult.%s, err = unmarshal_%s_elem(r, nested_elem)\n",
			field.odin_name,
			nested_lower,
		)
		fmt.sbprintf(sb, "\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t}}\n")
		fmt.sbprintf(sb, "\t}}\n\n")

	case .Array_Primitive:
		generate_array_primitive_read(sb, field, parent)

	case .Array_Struct:
		generate_array_struct_read(sb, field, parent)

	case .Dynamic_Primitive:
		generate_dynamic_primitive_read(sb, field, parent)

	case .Dynamic_Struct:
		generate_dynamic_struct_read(sb, field, parent)

	case .Fixed_Array_Primitive:
		generate_fixed_array_primitive_read(sb, field, parent)

	case .Fixed_Array_Struct:
		generate_fixed_array_struct_read(sb, field, parent)

	case .Unknown:
		fmt.sbprintf(sb, "\t// TODO: Unknown type for field %s\n\n", field.odin_name)
	}
}

generate_array_primitive_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
) {
	oj := g_ojson_prefix

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(
		sb,
		"\t\t\tresult.%s = make([]%s, len(items))\n",
		field.odin_name,
		field.element_type,
	)
	fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items {{\n")

	switch field.element_type {
	case "string":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_string_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "int":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_int_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "i64":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_i64_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "f64":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_f64_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "bool":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_bool_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case:
		if is_integer_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_i64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tresult.%s[i] = %s(val)\n",
				field.odin_name,
				field.element_type,
			)
		} else if is_float_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_f64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tresult.%s[i] = %s(val)\n",
				field.odin_name,
				field.element_type,
			)
		} else {
			fmt.sbprintf(sb, "\t\t\t\t// TODO: handle element type %s\n", field.element_type)
		}
	}

	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_array_struct_read :: proc(sb: ^strings.Builder, field: Field_Info, parent: Struct_Info) {
	oj := g_ojson_prefix
	tp := get_type_prefix(parent)
	elem_lower := to_snake_case(field.element_type)

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(
		sb,
		"\t\t\tresult.%s = make([]%s%s, len(items))\n",
		field.odin_name,
		tp,
		field.element_type,
	)
	fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items {{\n")
	fmt.sbprintf(
		sb,
		"\t\t\t\tresult.%s[i], err = unmarshal_%s_elem(r, item_elem)\n",
		field.odin_name,
		elem_lower,
	)
	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_dynamic_primitive_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
) {
	oj := g_ojson_prefix

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(
		sb,
		"\t\t\tresult.%s = make([dynamic]%s, 0, len(items))\n",
		field.odin_name,
		field.element_type,
	)
	fmt.sbprintf(sb, "\t\t\tfor item_elem in items {{\n")

	switch field.element_type {
	case "string":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_string_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case "int":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_int_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case "i64":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_i64_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case "f64":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_f64_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case "bool":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_bool_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case:
		if is_integer_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_i64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tappend(&result.%s, %s(val))\n",
				field.odin_name,
				field.element_type,
			)
		} else if is_float_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_f64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tappend(&result.%s, %s(val))\n",
				field.odin_name,
				field.element_type,
			)
		} else {
			fmt.sbprintf(sb, "\t\t\t\t// TODO: handle element type %s\n", field.element_type)
		}
	}

	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_dynamic_struct_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
) {
	oj := g_ojson_prefix
	tp := get_type_prefix(parent)
	elem_lower := to_snake_case(field.element_type)

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(
		sb,
		"\t\t\tresult.%s = make([dynamic]%s%s, 0, len(items))\n",
		field.odin_name,
		tp,
		field.element_type,
	)
	fmt.sbprintf(sb, "\t\t\tfor item_elem in items {{\n")
	fmt.sbprintf(sb, "\t\t\t\titem, item_err := unmarshal_%s_elem(r, item_elem)\n", elem_lower)
	fmt.sbprintf(sb, "\t\t\t\terr = item_err\n")
	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, item)\n", field.odin_name)
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_fixed_array_primitive_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
) {
	oj := g_ojson_prefix

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(sb, "\t\t\tcount := min(len(items), %d)\n", field.array_size)
	fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items[:count] {{\n")

	switch field.element_type {
	case "string":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_string_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "int":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_int_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "i64":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_i64_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "f64":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_f64_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "bool":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_bool_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case:
		if is_integer_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_i64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tresult.%s[i] = %s(val)\n",
				field.odin_name,
				field.element_type,
			)
		} else if is_float_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_f64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tresult.%s[i] = %s(val)\n",
				field.odin_name,
				field.element_type,
			)
		} else {
			fmt.sbprintf(sb, "\t\t\t\t// TODO: handle element type %s\n", field.element_type)
		}
	}

	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_fixed_array_struct_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
) {
	oj := g_ojson_prefix
	elem_lower := to_snake_case(field.element_type)

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(sb, "\t\t\tcount := min(len(items), %d)\n", field.array_size)
	fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items[:count] {{\n")
	fmt.sbprintf(
		sb,
		"\t\t\t\tresult.%s[i], err = unmarshal_%s_elem(r, item_elem)\n",
		field.odin_name,
		elem_lower,
	)
	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

to_snake_case :: proc(s: string, allocator := context.allocator) -> string {
	if len(s) == 0 {
		return ""
	}

	sb := strings.builder_make(allocator)

	for i := 0; i < len(s); i += 1 {
		c := s[i]
		if c >= 'A' && c <= 'Z' {
			if i > 0 {
				strings.write_byte(&sb, '_')
			}
			strings.write_byte(&sb, c + 32)
		} else {
			strings.write_byte(&sb, c)
		}
	}

	return strings.to_string(sb)
}

is_integer_type :: proc(type_name: string) -> bool {
	switch type_name {
	case "i8", "i16", "i32", "i64", "int", "u8", "u16", "u32", "u64", "uint":
		return true
	}
	return false
}

is_float_type :: proc(type_name: string) -> bool {
	switch type_name {
	case "f16", "f32", "f64":
		return true
	}
	return false
}
