package generate

import "core:fmt"
import fp "core:path/filepath"
import "core:strings"

Gen_Context :: struct {
	oj:           string,
	pkg_prefixes: map[string]string,
}

generate_code :: proc(
	structs: []Struct_Info,
	unions: []Union_Info,
	package_name: string,
	output_dir: string = "",
	ojson_import: string = "",
	allocator := context.allocator,
) -> string {
	sb := strings.builder_make(allocator)

	ctx: Gen_Context
	ctx.oj = ojson_import != "" ? "oj." : ""

	Package_Info :: struct {
		name:        string,
		source_dir:  string,
		import_path: string,
	}
	packages := make(map[string]Package_Info, allocator = allocator)
	defer delete(packages)

	for info in structs {
		if info.source_package == "" || info.source_dir == "" {
			continue
		}
		if info.source_package == package_name {
			continue
		}
		if info.source_dir not_in packages {
			import_path, _ := fp.rel(output_dir, info.source_dir)
			packages[info.source_dir] = Package_Info {
				name        = info.source_package,
				source_dir  = info.source_dir,
				import_path = import_path,
			}
		}
	}
	for info in unions {
		if info.source_package == "" || info.source_dir == "" {
			continue
		}
		if info.source_package == package_name {
			continue
		}
		if info.source_dir not_in packages {
			import_path, _ := fp.rel(output_dir, info.source_dir)
			packages[info.source_dir] = Package_Info {
				name        = info.source_package,
				source_dir  = info.source_dir,
				import_path = import_path,
			}
		}
	}

	ctx.pkg_prefixes = make(map[string]string, allocator = allocator)
	for dir, pkg in packages {
		ctx.pkg_prefixes[dir] = fmt.tprintf("%s.", pkg.name)
	}

	strings.write_string(&sb, "// Code generated by ojson generator. DO NOT EDIT.\n")
	strings.write_string(&sb, "package ")
	strings.write_string(&sb, package_name)
	strings.write_string(&sb, "\n\n")

	for _, pkg in packages {
		fmt.sbprintf(&sb, "import %s \"%s\"\n", pkg.name, pkg.import_path)
	}
	if ojson_import != "" {
		fmt.sbprintf(&sb, "import oj \"%s\"\n", ojson_import)
	}
	if len(packages) > 0 || ojson_import != "" {
		strings.write_string(&sb, "\n")
	}

	for info, i in unions {
		generate_union_unmarshal(&sb, info, &ctx)
		strings.write_string(&sb, "\n")
		generate_union_marshal(&sb, info, &ctx)
		if i < len(unions) - 1 || len(structs) > 0 {
			strings.write_string(&sb, "\n")
		}
	}

	for info, i in structs {
		generate_unmarshal_proc(&sb, info, &ctx)
		strings.write_string(&sb, "\n")
		generate_is_zero_proc(&sb, info, &ctx)
		strings.write_string(&sb, "\n")
		generate_marshal_proc(&sb, info, &ctx)
		if i < len(structs) - 1 {
			strings.write_string(&sb, "\n")
		}
	}

	return strings.to_string(sb)
}

generate_is_zero_proc :: proc(sb: ^strings.Builder, info: Struct_Info, ctx: ^Gen_Context) {
	lower_name := to_snake_case(info.name)
	type_prefix := get_type_prefix(info, ctx)
	type_name := fmt.tprintf("%s%s", type_prefix, info.name)

	fmt.sbprintf(sb, "is_zero_%s :: proc(v: %s) -> bool {{\n", lower_name, type_name)
	if info.is_tuple || len(info.fields) == 0 {
		strings.write_string(sb, "\treturn true\n")
		strings.write_string(sb, "}\n")
		return
	}
	strings.write_string(sb, "\treturn")
	for field, i in info.fields {
		check := is_zero_field_expr(field)
		if i > 0 {
			strings.write_string(sb, " &&")
		}
		fmt.sbprintf(sb, " %s", check)
	}
	strings.write_string(sb, "\n}\n")
}

is_zero_field_expr :: proc(field: Field_Info) -> string {
	#partial switch field.type_kind {
	case .String:
		return fmt.tprintf(`v.%s == ""`, field.odin_name)
	case .Int, .I64, .I8, .I16, .I32, .U8, .U16, .U32, .U64, .Uint, .F16, .F32, .F64:
		return fmt.tprintf("v.%s == 0", field.odin_name)
	case .Bool:
		return fmt.tprintf("!v.%s", field.odin_name)
	case .Enum, .Distinct:
		return fmt.tprintf("int(v.%s) == 0", field.odin_name)
	case .Array_Primitive, .Array_Struct, .Array_Union:
		return fmt.tprintf("len(v.%s) == 0", field.odin_name)
	case .Dynamic_Primitive, .Dynamic_Struct, .Dynamic_Union:
		return fmt.tprintf("len(v.%s) == 0", field.odin_name)
	case .Fixed_Array_Primitive, .Fixed_Array_Struct, .Fixed_Array_Union:
		return "true"
	case .Struct:
		return fmt.tprintf(
			"is_zero_%s(v.%s)",
			to_snake_case(field.type_name),
			field.odin_name,
		)
	case .Union:
		return fmt.tprintf("v.%s == nil", field.odin_name)
	}
	return "true"
}

get_type_prefix :: proc(info: Struct_Info, ctx: ^Gen_Context) -> string {
	if info.source_dir == "" {
		return ""
	}
	if prefix, ok := ctx.pkg_prefixes[info.source_dir]; ok {
		return prefix
	}
	return ""
}

generate_unmarshal_proc :: proc(sb: ^strings.Builder, info: Struct_Info, ctx: ^Gen_Context) {
	lower_name := to_snake_case(info.name)
	type_prefix := get_type_prefix(info, ctx)
	type_name := fmt.tprintf("%s%s", type_prefix, info.name)
	oj := ctx.oj

	fmt.sbprintf(sb, "// Unmarshals JSON into %s\n", info.name)
	if info.source_package != "" && info.source_file != "" {
		fmt.sbprintf(sb, "// Source: %s (%s)\n", info.source_package, info.source_file)
	}

	fmt.sbprintf(
		sb,
		"unmarshal_%s :: proc(r: ^%sReader, path: string = \"\") -> (result: %s, err: %sError) {{\n",
		lower_name,
		oj,
		type_name,
		oj,
	)
	fmt.sbprintf(sb, "\telem, elem_err := %selement_at(r, path)\n", oj)
	fmt.sbprintf(sb, "\tif elem_err != .OK do return result, elem_err\n")
	fmt.sbprintf(sb, "\treturn unmarshal_%s_elem(r, elem)\n", lower_name)
	fmt.sbprintf(sb, "}}\n\n")

	fmt.sbprintf(sb, "// Unmarshals JSON element into %s\n", info.name)

	fmt.sbprintf(
		sb,
		"unmarshal_%s_elem :: proc(r: ^%sReader, elem: %sElement) -> (result: %s, err: %sError) {{\n",
		lower_name,
		oj,
		oj,
		type_name,
		oj,
	)

	if info.is_tuple {
		generate_tuple_read(sb, info, ctx)
	} else {
		for field in info.fields {
			generate_field_read(sb, field, info, ctx)
		}
	}

	strings.write_string(sb, "\treturn\n")
	strings.write_string(sb, "}\n")
}

generate_tuple_read :: proc(sb: ^strings.Builder, info: Struct_Info, ctx: ^Gen_Context) {
	oj := ctx.oj

	fmt.sbprintf(sb, "\titems, items_err := %sarray_elements_from(r, elem)\n", oj)
	fmt.sbprintf(sb, "\tif items_err != .OK do return result, items_err\n\n")

	for field, i in info.fields {
		#partial switch field.type_kind {
		case .String:
			fmt.sbprintf(sb, "\tif len(items) > %d {{\n", i)
			fmt.sbprintf(
				sb,
				"\t\tresult.%s, err = %sread_string_value(r, items[%d])\n",
				field.odin_name,
				oj,
				i,
			)
			fmt.sbprintf(sb, "\t\tif err != .OK do return\n")
			fmt.sbprintf(sb, "\t}}\n\n")

		case .Int:
			fmt.sbprintf(sb, "\tif len(items) > %d {{\n", i)
			fmt.sbprintf(
				sb,
				"\t\tresult.%s, err = %sread_int_value(r, items[%d])\n",
				field.odin_name,
				oj,
				i,
			)
			fmt.sbprintf(sb, "\t\tif err != .OK do return\n")
			fmt.sbprintf(sb, "\t}}\n\n")

		case .I64:
			fmt.sbprintf(sb, "\tif len(items) > %d {{\n", i)
			fmt.sbprintf(
				sb,
				"\t\tresult.%s, err = %sread_i64_value(r, items[%d])\n",
				field.odin_name,
				oj,
				i,
			)
			fmt.sbprintf(sb, "\t\tif err != .OK do return\n")
			fmt.sbprintf(sb, "\t}}\n\n")

		case .F64:
			fmt.sbprintf(sb, "\tif len(items) > %d {{\n", i)
			fmt.sbprintf(
				sb,
				"\t\tresult.%s, err = %sread_f64_value(r, items[%d])\n",
				field.odin_name,
				oj,
				i,
			)
			fmt.sbprintf(sb, "\t\tif err != .OK do return\n")
			fmt.sbprintf(sb, "\t}}\n\n")

		case .Bool:
			fmt.sbprintf(sb, "\tif len(items) > %d {{\n", i)
			fmt.sbprintf(
				sb,
				"\t\tresult.%s, err = %sread_bool_value(r, items[%d])\n",
				field.odin_name,
				oj,
				i,
			)
			fmt.sbprintf(sb, "\t\tif err != .OK do return\n")
			fmt.sbprintf(sb, "\t}}\n\n")

		case .I8, .I16, .I32:
			fmt.sbprintf(sb, "\tif len(items) > %d {{\n", i)
			fmt.sbprintf(sb, "\t\tval: i64\n")
			fmt.sbprintf(sb, "\t\tval, err = %sread_i64_value(r, items[%d])\n", oj, i)
			fmt.sbprintf(sb, "\t\tif err != .OK do return\n")
			fmt.sbprintf(sb, "\t\tresult.%s = %s(val)\n", field.odin_name, field.type_name)
			fmt.sbprintf(sb, "\t}}\n\n")

		case .U8, .U16, .U32, .U64, .Uint:
			fmt.sbprintf(sb, "\tif len(items) > %d {{\n", i)
			fmt.sbprintf(sb, "\t\tval: i64\n")
			fmt.sbprintf(sb, "\t\tval, err = %sread_i64_value(r, items[%d])\n", oj, i)
			fmt.sbprintf(sb, "\t\tif err != .OK do return\n")
			fmt.sbprintf(sb, "\t\tresult.%s = %s(val)\n", field.odin_name, field.type_name)
			fmt.sbprintf(sb, "\t}}\n\n")

		case .F16, .F32:
			fmt.sbprintf(sb, "\tif len(items) > %d {{\n", i)
			fmt.sbprintf(sb, "\t\tval: f64\n")
			fmt.sbprintf(sb, "\t\tval, err = %sread_f64_value(r, items[%d])\n", oj, i)
			fmt.sbprintf(sb, "\t\tif err != .OK do return\n")
			fmt.sbprintf(sb, "\t\tresult.%s = %s(val)\n", field.odin_name, field.type_name)
			fmt.sbprintf(sb, "\t}}\n\n")

		case:
			fmt.sbprintf(
				sb,
				"\t// TODO: Tuple field %s (type %v) at index %d\n\n",
				field.odin_name,
				field.type_kind,
				i,
			)
		}
	}
}

generate_field_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj
	tp := get_type_prefix(parent, ctx)

	switch field.type_kind {
	case .String:
		if field.raw {
			fmt.sbprintf(sb, "\t{{\n")
			fmt.sbprintf(
				sb,
				"\t\traw_val, raw_err := %sread_raw_elem(r, elem, \"%s\")\n",
				oj,
				field.json_name,
			)
			strings.write_string(sb, "\t\tif raw_err != .OK && raw_err != .Key_Not_Found && raw_err != .Type_Mismatch do return result, raw_err\n")
			fmt.sbprintf(sb, "\t\tif raw_err == .OK do result.%s = raw_val\n", field.odin_name)
			fmt.sbprintf(sb, "\t}}\n\n")
		} else {
			fmt.sbprintf(
				sb,
				"\tresult.%s, err = %sread_string_elem(r, elem, \"%s\")\n",
				field.odin_name,
				oj,
				field.json_name,
			)
			strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n\n")
		}

	case .Int:
		fmt.sbprintf(
			sb,
			"\tresult.%s, err = %sread_int_elem(r, elem, \"%s\")\n",
			field.odin_name,
			oj,
			field.json_name,
		)
		strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n\n")

	case .I64:
		fmt.sbprintf(
			sb,
			"\tresult.%s, err = %sread_i64_elem(r, elem, \"%s\")\n",
			field.odin_name,
			oj,
			field.json_name,
		)
		strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n\n")

	case .F64:
		fmt.sbprintf(
			sb,
			"\tresult.%s, err = %sread_f64_elem(r, elem, \"%s\")\n",
			field.odin_name,
			oj,
			field.json_name,
		)
		strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n\n")

	case .Bool:
		fmt.sbprintf(
			sb,
			"\tresult.%s, err = %sread_bool_elem(r, elem, \"%s\")\n",
			field.odin_name,
			oj,
			field.json_name,
		)
		strings.write_string(sb, "\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n\n")

	case .I8, .I16, .I32:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: i64\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_i64_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s(val)\n",
			field.odin_name,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .U8, .U16, .U32, .U64, .Uint:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: i64\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_i64_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s(val)\n",
			field.odin_name,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .F16, .F32:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: f64\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_f64_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s(val)\n",
			field.odin_name,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .Enum:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: int\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_int_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s%s(val)\n",
			field.odin_name,
			tp,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .Distinct:
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(sb, "\t\tval: int\n")
		fmt.sbprintf(sb, "\t\tval, err = %sread_int_elem(r, elem, \"%s\")\n", oj, field.json_name)
		strings.write_string(sb, "\t\tif err != .OK && err != .Key_Not_Found && err != .Type_Mismatch do return\n")
		fmt.sbprintf(
			sb,
			"\t\tif err == .OK do result.%s = %s%s(val)\n",
			field.odin_name,
			tp,
			field.type_name,
		)
		fmt.sbprintf(sb, "\t}}\n\n")

	case .Struct:
		nested_lower := to_snake_case(field.type_name)
		fmt.sbprintf(sb, "\t{{\n")
		fmt.sbprintf(
			sb,
			"\t\tnested_elem, nested_err := %sobj_element_from(r, elem, \"%s\")\n",
			oj,
			field.json_name,
		)
		fmt.sbprintf(sb, "\t\tif nested_err == .OK {{\n")
		fmt.sbprintf(
			sb,
			"\t\t\tresult.%s, err = unmarshal_%s_elem(r, nested_elem)\n",
			field.odin_name,
			nested_lower,
		)
		fmt.sbprintf(sb, "\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t}}\n")
		fmt.sbprintf(sb, "\t}}\n\n")

	case .Array_Primitive:
		generate_array_primitive_read(sb, field, parent, ctx)

	case .Array_Struct:
		generate_array_struct_read(sb, field, parent, ctx)

	case .Dynamic_Primitive:
		generate_dynamic_primitive_read(sb, field, parent, ctx)

	case .Dynamic_Struct:
		generate_dynamic_struct_read(sb, field, parent, ctx)

	case .Fixed_Array_Primitive:
		generate_fixed_array_primitive_read(sb, field, parent, ctx)

	case .Fixed_Array_Struct:
		generate_fixed_array_struct_read(sb, field, parent, ctx)

	case .Union:
		generate_union_field_read(sb, field, ctx)

	case .Array_Union, .Dynamic_Union, .Fixed_Array_Union:
		generate_union_array_read(sb, field, parent, ctx)

	case .Unknown:
		fmt.sbprintf(sb, "\t// TODO: Unknown type for field %s\n\n", field.odin_name)
	}
}

generate_array_primitive_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(
		sb,
		"\t\t\tresult.%s = make([]%s, len(items))\n",
		field.odin_name,
		field.element_type,
	)
	fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items {{\n")

	switch field.element_type {
	case "string":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_string_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "int":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_int_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "i64":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_i64_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "f64":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_f64_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "bool":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_bool_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case:
		if is_integer_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_i64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tresult.%s[i] = %s(val)\n",
				field.odin_name,
				field.element_type,
			)
		} else if is_float_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_f64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tresult.%s[i] = %s(val)\n",
				field.odin_name,
				field.element_type,
			)
		} else {
			fmt.sbprintf(sb, "\t\t\t\t// TODO: handle element type %s\n", field.element_type)
		}
	}

	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_array_struct_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj
	tp := get_type_prefix(parent, ctx)
	elem_lower := to_snake_case(field.element_type)

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(
		sb,
		"\t\t\tresult.%s = make([]%s%s, len(items))\n",
		field.odin_name,
		tp,
		field.element_type,
	)
	fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items {{\n")
	fmt.sbprintf(
		sb,
		"\t\t\t\tresult.%s[i], err = unmarshal_%s_elem(r, item_elem)\n",
		field.odin_name,
		elem_lower,
	)
	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_dynamic_primitive_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(
		sb,
		"\t\t\tresult.%s = make([dynamic]%s, 0, len(items))\n",
		field.odin_name,
		field.element_type,
	)
	fmt.sbprintf(sb, "\t\t\tfor item_elem in items {{\n")

	switch field.element_type {
	case "string":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_string_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case "int":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_int_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case "i64":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_i64_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case "f64":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_f64_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case "bool":
		fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_bool_elem(r, item_elem, \"\")\n", oj)
		fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, val)\n", field.odin_name)
	case:
		if is_integer_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_i64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tappend(&result.%s, %s(val))\n",
				field.odin_name,
				field.element_type,
			)
		} else if is_float_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_f64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tappend(&result.%s, %s(val))\n",
				field.odin_name,
				field.element_type,
			)
		} else {
			fmt.sbprintf(sb, "\t\t\t\t// TODO: handle element type %s\n", field.element_type)
		}
	}

	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_dynamic_struct_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj
	tp := get_type_prefix(parent, ctx)
	elem_lower := to_snake_case(field.element_type)

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(
		sb,
		"\t\t\tresult.%s = make([dynamic]%s%s, 0, len(items))\n",
		field.odin_name,
		tp,
		field.element_type,
	)
	fmt.sbprintf(sb, "\t\t\tfor item_elem in items {{\n")
	fmt.sbprintf(sb, "\t\t\t\titem, item_err := unmarshal_%s_elem(r, item_elem)\n", elem_lower)
	fmt.sbprintf(sb, "\t\t\t\terr = item_err\n")
	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, item)\n", field.odin_name)
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_fixed_array_primitive_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(sb, "\t\t\tcount := min(len(items), %d)\n", field.array_size)
	fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items[:count] {{\n")

	switch field.element_type {
	case "string":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_string_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "int":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_int_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "i64":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_i64_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "f64":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_f64_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case "bool":
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = %sread_bool_elem(r, item_elem, \"\")\n",
			field.odin_name,
			oj,
		)
	case:
		if is_integer_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_i64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tresult.%s[i] = %s(val)\n",
				field.odin_name,
				field.element_type,
			)
		} else if is_float_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t\t\tval, read_err := %sread_f64_elem(r, item_elem, \"\")\n", oj)
			fmt.sbprintf(sb, "\t\t\t\terr = read_err\n")
			fmt.sbprintf(
				sb,
				"\t\t\t\tresult.%s[i] = %s(val)\n",
				field.odin_name,
				field.element_type,
			)
		} else {
			fmt.sbprintf(sb, "\t\t\t\t// TODO: handle element type %s\n", field.element_type)
		}
	}

	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_fixed_array_struct_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj
	elem_lower := to_snake_case(field.element_type)

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)
	fmt.sbprintf(sb, "\t\t\tcount := min(len(items), %d)\n", field.array_size)
	fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items[:count] {{\n")
	fmt.sbprintf(
		sb,
		"\t\t\t\tresult.%s[i], err = unmarshal_%s_elem(r, item_elem)\n",
		field.odin_name,
		elem_lower,
	)
	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

to_snake_case :: proc(s: string, allocator := context.allocator) -> string {
	if len(s) == 0 {
		return ""
	}

	sb := strings.builder_make(allocator)

	for i := 0; i < len(s); i += 1 {
		c := s[i]
		if c >= 'A' && c <= 'Z' {
			if i > 0 {
				prev := s[i - 1]
				if (prev >= 'a' && prev <= 'z') || (prev >= '0' && prev <= '9') {
					strings.write_byte(&sb, '_')
				}
			}
			strings.write_byte(&sb, c + 32)
		} else {
			strings.write_byte(&sb, c)
		}
	}

	return strings.to_string(sb)
}

is_integer_type :: proc(type_name: string) -> bool {
	switch type_name {
	case "i8", "i16", "i32", "i64", "int", "u8", "u16", "u32", "u64", "uint":
		return true
	}
	return false
}

is_float_type :: proc(type_name: string) -> bool {
	switch type_name {
	case "f16", "f32", "f64":
		return true
	}
	return false
}

generate_marshal_proc :: proc(sb: ^strings.Builder, info: Struct_Info, ctx: ^Gen_Context) {
	lower_name := to_snake_case(info.name)
	type_prefix := get_type_prefix(info, ctx)
	type_name := fmt.tprintf("%s%s", type_prefix, info.name)
	oj := ctx.oj

	fmt.sbprintf(sb, "// Marshals %s to JSON\n", info.name)
	fmt.sbprintf(sb, "marshal_%s :: proc(w: ^%sWriter, value: %s) {{\n", lower_name, oj, type_name)

	if info.is_tuple {
		generate_tuple_write(sb, info, ctx)
	} else {
		fmt.sbprintf(sb, "\t%swrite_object_start(w)\n", oj)
		for field in info.fields {
			generate_field_write(sb, field, info, ctx)
		}
		fmt.sbprintf(sb, "\t%swrite_object_end(w)\n", oj)
	}

	strings.write_string(sb, "}\n")
}

generate_tuple_write :: proc(sb: ^strings.Builder, info: Struct_Info, ctx: ^Gen_Context) {
	oj := ctx.oj

	fmt.sbprintf(sb, "\t%swrite_array_start(w)\n", oj)
	for field in info.fields {
		generate_value_write(sb, field, fmt.tprintf("value.%s", field.odin_name), ctx)
	}
	fmt.sbprintf(sb, "\t%swrite_array_end(w)\n", oj)
}

omitempty_zero_check :: proc(field: Field_Info) -> (check: string, has_check: bool) {
	#partial switch field.type_kind {
	case .String:
		return fmt.tprintf(`value.%s != ""`, field.odin_name), true
	case .Int, .I64, .I8, .I16, .I32, .U8, .U16, .U32, .U64, .Uint, .F16, .F32, .F64:
		return fmt.tprintf("value.%s != 0", field.odin_name), true
	case .Bool:
		return fmt.tprintf("value.%s", field.odin_name), true
	case .Enum, .Distinct:
		return fmt.tprintf("int(value.%s) != 0", field.odin_name), true
	case .Array_Primitive, .Array_Struct, .Array_Union:
		return fmt.tprintf("len(value.%s) > 0", field.odin_name), true
	case .Dynamic_Primitive, .Dynamic_Struct, .Dynamic_Union:
		return fmt.tprintf("len(value.%s) > 0", field.odin_name), true
	case .Struct:
		return fmt.tprintf(
				"!is_zero_%s(value.%s)",
				to_snake_case(field.type_name),
				field.odin_name,
			), true
	case .Union:
		return fmt.tprintf("value.%s != nil", field.odin_name), true
	}
	return "", false
}

generate_field_write :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj
	indent := "\t"

	if field.omitempty {
		check, has_check := omitempty_zero_check(field)
		if has_check {
			fmt.sbprintf(sb, "\tif %s {{\n", check)
			indent = "\t\t"
		}
	}

	fmt.sbprintf(sb, "%s%swrite_key(w, \"%s\")\n", indent, oj, field.json_name)

	switch field.type_kind {
	case .String:
		if field.union_tag != "" {
			fmt.sbprintf(sb, "%s%swrite_string(w, \"%s\")\n", indent, oj, field.union_tag)
		} else if field.raw {
			fmt.sbprintf(sb, "%s%swrite_raw(w, value.%s)\n", indent, oj, field.odin_name)
		} else {
			fmt.sbprintf(sb, "%s%swrite_string(w, value.%s)\n", indent, oj, field.odin_name)
		}
	case .Int:
		fmt.sbprintf(sb, "%s%swrite_int(w, value.%s)\n", indent, oj, field.odin_name)
	case .Bool:
		fmt.sbprintf(sb, "%s%swrite_bool(w, value.%s)\n", indent, oj, field.odin_name)
	case .F32:
		fmt.sbprintf(sb, "%s%swrite_f32(w, value.%s)\n", indent, oj, field.odin_name)
	case .F64:
		fmt.sbprintf(sb, "%s%swrite_f64(w, value.%s)\n", indent, oj, field.odin_name)
	case .I64, .I8, .I16, .I32, .U8, .U16, .U32, .U64, .Uint:
		fmt.sbprintf(sb, "%s%swrite_int(w, int(value.%s))\n", indent, oj, field.odin_name)
	case .F16:
		fmt.sbprintf(sb, "%s%swrite_f32(w, f32(value.%s))\n", indent, oj, field.odin_name)
	case .Enum, .Distinct:
		fmt.sbprintf(sb, "%s%swrite_int(w, int(value.%s))\n", indent, oj, field.odin_name)
	case .Struct:
		nested_lower := to_snake_case(field.type_name)
		fmt.sbprintf(sb, "%smarshal_%s(w, value.%s)\n", indent, nested_lower, field.odin_name)
	case .Array_Primitive, .Dynamic_Primitive, .Fixed_Array_Primitive:
		generate_array_primitive_write(sb, field, ctx)
	case .Array_Struct, .Dynamic_Struct, .Fixed_Array_Struct:
		generate_array_struct_write(sb, field, ctx)
	case .Union:
		generate_union_field_write(sb, field, indent, ctx)
	case .Array_Union, .Dynamic_Union, .Fixed_Array_Union:
		generate_union_array_write(sb, field, indent, ctx)
	case .Unknown:
		fmt.sbprintf(sb, "%s// TODO: Unknown type for field %s\n", indent, field.odin_name)
	}

	if field.omitempty {
		_, has_check := omitempty_zero_check(field)
		if has_check {
			fmt.sbprintf(sb, "\t}}\n")
		}
	}
}

generate_value_write :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	expr: string,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj

	#partial switch field.type_kind {
	case .String:
		fmt.sbprintf(sb, "\t%swrite_string(w, %s)\n", oj, expr)
	case .Int:
		fmt.sbprintf(sb, "\t%swrite_int(w, %s)\n", oj, expr)
	case .Bool:
		fmt.sbprintf(sb, "\t%swrite_bool(w, %s)\n", oj, expr)
	case .F32:
		fmt.sbprintf(sb, "\t%swrite_f32(w, %s)\n", oj, expr)
	case .F64:
		fmt.sbprintf(sb, "\t%swrite_f64(w, %s)\n", oj, expr)
	case .I64, .I8, .I16, .I32, .U8, .U16, .U32, .U64, .Uint:
		fmt.sbprintf(sb, "\t%swrite_int(w, int(%s))\n", oj, expr)
	case .F16:
		fmt.sbprintf(sb, "\t%swrite_f32(w, f32(%s))\n", oj, expr)
	case .Enum, .Distinct:
		fmt.sbprintf(sb, "\t%swrite_int(w, int(%s))\n", oj, expr)
	case:
		fmt.sbprintf(sb, "\t// TODO: tuple field type %v\n", field.type_kind)
	}
}

generate_array_primitive_write :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj

	fmt.sbprintf(sb, "\t%swrite_array_start(w)\n", oj)
	fmt.sbprintf(sb, "\tfor item in value.%s {{\n", field.odin_name)

	switch field.element_type {
	case "string":
		fmt.sbprintf(sb, "\t\t%swrite_string(w, item)\n", oj)
	case "int":
		fmt.sbprintf(sb, "\t\t%swrite_int(w, item)\n", oj)
	case "i64":
		fmt.sbprintf(sb, "\t\t%swrite_int(w, int(item))\n", oj)
	case "f32":
		fmt.sbprintf(sb, "\t\t%swrite_f32(w, item)\n", oj)
	case "f64":
		fmt.sbprintf(sb, "\t\t%swrite_f64(w, item)\n", oj)
	case "bool":
		fmt.sbprintf(sb, "\t\t%swrite_bool(w, item)\n", oj)
	case:
		if is_integer_type(field.element_type) {
			fmt.sbprintf(sb, "\t\t%swrite_int(w, int(item))\n", oj)
		} else if is_float_type(field.element_type) {
			elem := field.element_type
			if elem == "f16" {
				fmt.sbprintf(sb, "\t\t%swrite_f32(w, f32(item))\n", oj)
			} else {
				fmt.sbprintf(sb, "\t\t%swrite_f32(w, item)\n", oj)
			}
		} else {
			fmt.sbprintf(sb, "\t\t// TODO: handle element type %s\n", field.element_type)
		}
	}

	fmt.sbprintf(sb, "\t}}\n")
	fmt.sbprintf(sb, "\t%swrite_array_end(w)\n", oj)
}

generate_array_struct_write :: proc(sb: ^strings.Builder, field: Field_Info, ctx: ^Gen_Context) {
	oj := ctx.oj
	elem_lower := to_snake_case(field.element_type)

	fmt.sbprintf(sb, "\t%swrite_array_start(w)\n", oj)
	fmt.sbprintf(sb, "\tfor item in value.%s {{\n", field.odin_name)
	fmt.sbprintf(sb, "\t\tmarshal_%s(w, item)\n", elem_lower)
	fmt.sbprintf(sb, "\t}}\n")
	fmt.sbprintf(sb, "\t%swrite_array_end(w)\n", oj)
}

generate_union_field_read :: proc(sb: ^strings.Builder, field: Field_Info, ctx: ^Gen_Context) {
	oj := ctx.oj
	union_lower := to_snake_case(field.type_name)
	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tnested_elem, nested_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif nested_err == .OK {{\n")
	fmt.sbprintf(
		sb,
		"\t\t\tresult.%s, err = unmarshal_%s_elem(r, nested_elem)\n",
		field.odin_name,
		union_lower,
	)
	fmt.sbprintf(sb, "\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_union_array_read :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	parent: Struct_Info,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj
	tp := get_type_prefix(parent, ctx)
	union_lower := to_snake_case(field.element_type)
	is_fixed := field.type_kind == .Fixed_Array_Union
	is_dynamic := field.type_kind == .Dynamic_Union

	fmt.sbprintf(sb, "\t{{\n")
	fmt.sbprintf(
		sb,
		"\t\tarr_elem, arr_err := %sobj_element_from(r, elem, \"%s\")\n",
		oj,
		field.json_name,
	)
	fmt.sbprintf(sb, "\t\tif arr_err == .OK {{\n")
	fmt.sbprintf(sb, "\t\t\titems, _ := %sarray_elements_from(r, arr_elem)\n", oj)

	if is_fixed {
		fmt.sbprintf(sb, "\t\t\tcount := min(len(items), %d)\n", field.array_size)
		fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items[:count] {{\n")
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = unmarshal_%s_elem(r, item_elem)\n",
			field.odin_name,
			union_lower,
		)
	} else if is_dynamic {
		fmt.sbprintf(
			sb,
			"\t\t\tresult.%s = make([dynamic]%s%s, 0, len(items))\n",
			field.odin_name,
			tp,
			field.element_type,
		)
		fmt.sbprintf(sb, "\t\t\tfor item_elem in items {{\n")
		fmt.sbprintf(sb, "\t\t\t\titem, item_err := unmarshal_%s_elem(r, item_elem)\n", union_lower)
		fmt.sbprintf(sb, "\t\t\t\terr = item_err\n")
		fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
		fmt.sbprintf(sb, "\t\t\t\tappend(&result.%s, item)\n", field.odin_name)
	} else {
		fmt.sbprintf(
			sb,
			"\t\t\tresult.%s = make([]%s%s, len(items))\n",
			field.odin_name,
			tp,
			field.element_type,
		)
		fmt.sbprintf(sb, "\t\t\tfor item_elem, i in items {{\n")
		fmt.sbprintf(
			sb,
			"\t\t\t\tresult.%s[i], err = unmarshal_%s_elem(r, item_elem)\n",
			field.odin_name,
			union_lower,
		)
	}

	fmt.sbprintf(sb, "\t\t\t\tif err != .OK do return\n")
	fmt.sbprintf(sb, "\t\t\t}}\n")
	fmt.sbprintf(sb, "\t\t}}\n")
	fmt.sbprintf(sb, "\t}}\n\n")
}

generate_union_field_write :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	indent: string,
	ctx: ^Gen_Context,
) {
	union_lower := to_snake_case(field.type_name)
	fmt.sbprintf(sb, "%smarshal_%s(w, value.%s)\n", indent, union_lower, field.odin_name)
}

generate_union_array_write :: proc(
	sb: ^strings.Builder,
	field: Field_Info,
	indent: string,
	ctx: ^Gen_Context,
) {
	oj := ctx.oj
	union_lower := to_snake_case(field.element_type)
	fmt.sbprintf(sb, "%s%swrite_array_start(w)\n", indent, oj)
	fmt.sbprintf(sb, "%sfor item in value.%s {{\n", indent, field.odin_name)
	fmt.sbprintf(sb, "%s\tmarshal_%s(w, item)\n", indent, union_lower)
	fmt.sbprintf(sb, "%s}}\n", indent)
	fmt.sbprintf(sb, "%s%swrite_array_end(w)\n", indent, oj)
}

generate_union_unmarshal :: proc(sb: ^strings.Builder, info: Union_Info, ctx: ^Gen_Context) {
	lower_name := to_snake_case(info.name)
	type_prefix := union_type_prefix(info, ctx)
	type_name := fmt.tprintf("%s%s", type_prefix, info.name)
	oj := ctx.oj

	fmt.sbprintf(sb, "// Unmarshals JSON into %s (tagged union)\n", info.name)
	if info.source_package != "" && info.source_file != "" {
		fmt.sbprintf(sb, "// Source: %s (%s)\n", info.source_package, info.source_file)
	}

	fmt.sbprintf(
		sb,
		"unmarshal_%s :: proc(r: ^%sReader, path: string = \"\") -> (result: %s, err: %sError) {{\n",
		lower_name,
		oj,
		type_name,
		oj,
	)
	fmt.sbprintf(sb, "\telem, elem_err := %selement_at(r, path)\n", oj)
	fmt.sbprintf(sb, "\tif elem_err != .OK do return result, elem_err\n")
	fmt.sbprintf(sb, "\treturn unmarshal_%s_elem(r, elem)\n", lower_name)
	fmt.sbprintf(sb, "}}\n\n")

	fmt.sbprintf(sb, "// Unmarshals JSON element into %s (tagged union)\n", info.name)
	fmt.sbprintf(
		sb,
		"unmarshal_%s_elem :: proc(r: ^%sReader, elem: %sElement) -> (result: %s, err: %sError) {{\n",
		lower_name,
		oj,
		oj,
		type_name,
		oj,
	)
	fmt.sbprintf(sb, "\tdiscr, _ := %sread_string_elem(r, elem, \"%s\")\n", oj, info.discriminator)
	fmt.sbprintf(sb, "\tswitch discr {{\n")
	for v in info.variants {
		variant_lower := to_snake_case(v.struct_name)
		fmt.sbprintf(sb, "\tcase \"%s\":\n", v.tag)
		fmt.sbprintf(sb, "\t\tvariant, v_err := unmarshal_%s_elem(r, elem)\n", variant_lower)
		fmt.sbprintf(sb, "\t\tresult = variant\n")
		fmt.sbprintf(sb, "\t\terr = v_err\n")
	}
	fmt.sbprintf(sb, "\t}}\n")
	fmt.sbprintf(sb, "\treturn\n")
	fmt.sbprintf(sb, "}}\n")
}

generate_union_marshal :: proc(sb: ^strings.Builder, info: Union_Info, ctx: ^Gen_Context) {
	lower_name := to_snake_case(info.name)
	type_prefix := union_type_prefix(info, ctx)
	type_name := fmt.tprintf("%s%s", type_prefix, info.name)
	oj := ctx.oj

	fmt.sbprintf(sb, "// Marshals %s (tagged union) to JSON\n", info.name)
	fmt.sbprintf(sb, "marshal_%s :: proc(w: ^%sWriter, value: %s) {{\n", lower_name, oj, type_name)
	fmt.sbprintf(sb, "\tswitch variant in value {{\n")
	for v in info.variants {
		variant_lower := to_snake_case(v.struct_name)
		fmt.sbprintf(sb, "\tcase %s%s:\n", type_prefix, v.struct_name)
		fmt.sbprintf(sb, "\t\tmarshal_%s(w, variant)\n", variant_lower)
	}
	fmt.sbprintf(sb, "\t}}\n")
	fmt.sbprintf(sb, "}}\n")
}

union_type_prefix :: proc(info: Union_Info, ctx: ^Gen_Context) -> string {
	if info.source_dir == "" {
		return ""
	}
	if prefix, ok := ctx.pkg_prefixes[info.source_dir]; ok {
		return prefix
	}
	return ""
}
